# Generated by Django 4.2.4 on 2023-09-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "cantidad_stock",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad en stock"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "preciou",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "lead_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tiempo de retorno"
                    ),
                ),
                (
                    "agotado",
                    models.BooleanField(default=False, verbose_name="¿Está Agotado?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Folio"
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cliente"
                    ),
                ),
                (
                    "cantidad_pedida",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad pedida"
                    ),
                ),
                (
                    "compra_unica",
                    models.BooleanField(default=True, verbose_name="¿Es compra única?"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_orden",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de orden",
                    ),
                ),
                (
                    "cantidad_requerida",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad requerida"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordencompra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.ordencompra",
                    ),
                ),
                (
                    "pedidocliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.pedidocliente",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.material",
                    ),
                ),
            ],
        ),
    ]
