# Generated by Django 4.2.4 on 2023-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="lead_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Tiempo de retorno"
            ),
        ),
        migrations.DeleteModel(
            name="Almacen",
        ),
    ]
