# Generated by Django 4.2.4 on 2023-09-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_material_lead_time_delete_almacen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="lead_time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Tiempo de retorno"
            ),
        ),
    ]
