# Generated by Django 4.2.4 on 2023-09-25 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_alter_material_lead_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="fecha",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Fecha",
            ),
        ),
        migrations.AddField(
            model_name="pedidocliente",
            name="fecha",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Fecha",
            ),
        ),
    ]
