# Generated by Django 4.2.4 on 2023-09-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.categoria",
            ),
        ),
    ]
