# Generated by Django 4.2.4 on 2023-09-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_material_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Descripción"
            ),
        ),
    ]
