# Generated by Django 4.2.4 on 2023-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_alter_categoria_descripcion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="agotado",
        ),
        migrations.RemoveField(
            model_name="material",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="material",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="material",
            name="lead_time",
        ),
        migrations.RemoveField(
            model_name="material",
            name="preciou",
        ),
        migrations.AddField(
            model_name="material",
            name="clave",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Clave"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="genero",
            field=models.CharField(
                choices=[
                    ("Hule", "Productos de Hule"),
                    ("Espumas Autoadheribles", "Espumas Autoadheribles"),
                    ("Piezas Troqueladas", "Piezas Troqueladas"),
                    ("Empaque", "Productos para Empaque"),
                    ("Juntas Metálicas", "Juntas Metálicas"),
                    ("Aislamientos Térmicos", "Aislamientos Térmicos"),
                    ("Sellos Empaques", "Sellos o Empaques"),
                    ("Unicel", "Productos de Unicel"),
                    ("PTFE", "Productos PTFE"),
                    ("Especiales", "Productos Especiales"),
                ],
                default="Hule",
                max_length=25,
                verbose_name="Categoría",
            ),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
