# Generated by Django 4.2.4 on 2023-10-02 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_remove_material_agotado_remove_material_categoria_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="genero",
            new_name="categoria",
        ),
    ]
