# Generated by Django 4.2.4 on 2023-10-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0011_alter_material_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="proveedor",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Proveedor"
            ),
        ),
    ]
